# Generated by Django 3.1.2 on 2021-01-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('datahora', models.DateTimeField(blank=True)),
                ('linkmeet', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('datahora', models.DateTimeField(blank=True)),
                ('totaldehoras', models.IntegerField(blank=True, max_length=4)),
                ('aulas', models.ManyToManyField(blank=True, related_name='aula', to='apihacka.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('googleid', models.CharField(blank=True, max_length=5000)),
                ('tipousuario', models.CharField(blank=True, choices=[('Aluno', 'Aluno'), ('Empresa', 'Empresa'), ('Professor', 'Professor')], max_length=255)),
                ('cursos', models.ManyToManyField(blank=True, related_name='_usuario_cursos_+', to='apihacka.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('nota', models.IntegerField(blank=True, max_length=2)),
                ('linkaluno', models.CharField(blank=True, max_length=500)),
                ('aluno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apihacka.usuario')),
                ('aula', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apihacka.aula')),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apihacka.curso')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apihacka.curso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='relacaoaluno',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apihacka.usuario_aula'),
        ),
    ]
