# Generated by Django 3.1.2 on 2021-01-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('datahora', models.DateTimeField(blank=True)),
                ('linkmeet', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('datahora', models.DateTimeField(blank=True)),
                ('aulas', models.ManyToManyField(blank=True, related_name='aula', to='apihacka.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=255)),
                ('nota', models.IntegerField(blank=True, max_length=2)),
                ('linkaluno', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('googleid', models.CharField(blank=True, max_length=500)),
                ('cursos', models.ManyToManyField(blank=True, to='apihacka.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apihacka.curso'),
        ),
    ]
