# Generated by Django 3.1.2 on 2021-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
