# Generated by Django 3.1.2 on 2021-01-17 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0002_curso_informacoesaulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='aluno',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apihacka.usuario'),
            preserve_default=False,
        ),
    ]
