# Generated by Django 3.1.2 on 2021-01-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0003_remove_aula_relacaoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='relacaoaluno',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apihacka.usuario_aula'),
            preserve_default=False,
        ),
    ]
