# Generated by Django 3.1.2 on 2021-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0004_aula_relacaoaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='relacaoaluno',
        ),
        migrations.AddField(
            model_name='aula',
            name='relacaoaluno',
            field=models.ManyToManyField(blank=True, related_name='_aula_relacaoaluno_+', to='apihacka.Usuario_Aula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dadosusuario',
            field=models.ManyToManyField(blank=True, related_name='aula', to='apihacka.Curso'),
        ),
    ]
