# Generated by Django 3.1.2 on 2021-01-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0004_auto_20210117_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_aula',
            name='aula',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apihacka.aula'),
            preserve_default=False,
        ),
    ]
