# Generated by Django 3.1.2 on 2021-01-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0005_usuario_aula_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_aula',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apihacka.curso'),
            preserve_default=False,
        ),
    ]
