# Generated by Django 3.1.2 on 2021-01-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0005_auto_20210117_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='relacaoaluno',
        ),
    ]
