# Generated by Django 3.1.2 on 2021-01-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0006_remove_aula_relacaoaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='dadosusuario',
        ),
    ]
