# Generated by Django 3.1.2 on 2021-01-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0006_usuario_aula_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='informacoesaulas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipousuario',
            field=models.CharField(blank=True, choices=[('Aluno', 'Aluno'), ('Empresa', 'Empresa'), ('Professor', 'Professor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario_aula',
            name='presente',
            field=models.CharField(blank=True, choices=[('Aluno', 'Aluno'), ('Empresa', 'Empresa'), ('Professor', 'Professor')], max_length=255),
        ),
    ]
