# Generated by Django 3.1.2 on 2021-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0007_auto_20210117_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_aula',
            name='presente',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=255),
        ),
    ]
