# Generated by Django 3.1.2 on 2021-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0008_auto_20210117_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='totaldehoras',
            field=models.IntegerField(blank=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
