# Generated by Django 3.1.2 on 2021-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihacka', '0009_curso_totaldehoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='totaldehoras',
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
